#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
WEB_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
REPO_DIR=$(cd "$WEB_DIR/.." && pwd)
SMART_METER_DIR="$REPO_DIR/smart-meter"

CONTAINER_NAME="${KWDB_DEV_CONTAINER:-smart-meter-web-kwdb}"
IMAGE="${KWDB_DEV_IMAGE:-kwdb/kwdb:latest}"
SQL_PORT="${KWDB_DEV_SQL_PORT:-26257}"
HTTP_PORT="${KWDB_DEV_HTTP_PORT:-8080}"
CONTAINER_STORE="${KWDB_DEV_CONTAINER_STORE:-/kwdb-data}"
KWBASE_BIN="${KWDB_DEV_KWBASE_BIN:-/kaiwudb/bin/kwbase}"
LOCAL_DATA_DIR="${KWDB_DEV_DATA_DIR:-$WEB_DIR/.dev/kwdb-data}"
SERVER_ENV="$WEB_DIR/server/.env"

usage() {
  cat <<EOF
Usage:
  bash scripts/dev-kwdb.sh up
  bash scripts/dev-kwdb.sh reset
  bash scripts/dev-kwdb.sh stop
  bash scripts/dev-kwdb.sh status
  bash scripts/dev-kwdb.sh logs

Commands:
  up      Start an empty KWDB container if needed, then import smart-meter data.
  reset   Recreate the KWDB container from an empty store, then import data.
  stop    Stop the development KWDB container.
  status  Show container status and database tables.
  logs    Show recent KWDB container logs.

Environment overrides:
  KWDB_DEV_CONTAINER       Default: smart-meter-web-kwdb
  KWDB_DEV_IMAGE           Default: kwdb/kwdb:latest
  KWDB_DEV_SQL_PORT        Default: 26257
  KWDB_DEV_HTTP_PORT       Default: 8080
  KWDB_DEV_DATA_DIR        Default: smart-meter-web/.dev/kwdb-data
EOF
}

die() {
  echo "Error: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "command not found: $1"
}

container_exists() {
  docker inspect "$CONTAINER_NAME" >/dev/null 2>&1
}

container_running() {
  [ "$(docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null || true)" = "true" ]
}

sql() {
  docker exec "$CONTAINER_NAME" "$KWBASE_BIN" sql --insecure --host=localhost:"$SQL_PORT" "$@"
}

prepare_data() {
  local rdb_archive="$SMART_METER_DIR/extern/rdb.tar.gz"
  local tsdb_archive="$SMART_METER_DIR/extern/tsdb.tar.gz"
  local extern_dir="$LOCAL_DATA_DIR/extern"

  [ -f "$rdb_archive" ] || die "missing data archive: $rdb_archive"
  [ -f "$tsdb_archive" ] || die "missing data archive: $tsdb_archive"

  mkdir -p "$extern_dir"
  rm -rf "$extern_dir/rdb" "$extern_dir/tsdb"
  tar -xzf "$rdb_archive" -C "$extern_dir"
  tar -xzf "$tsdb_archive" -C "$extern_dir"
}

start_container() {
  if container_exists; then
    if container_running; then
      echo "KWDB development container is already running: $CONTAINER_NAME"
      return
    fi

    echo "Starting existing KWDB development container: $CONTAINER_NAME"
    docker start "$CONTAINER_NAME" >/dev/null
    return
  fi

  echo "Starting empty KWDB development container: $CONTAINER_NAME"
  docker run -d \
    --name "$CONTAINER_NAME" \
    -p "$SQL_PORT:$SQL_PORT" \
    -p "$HTTP_PORT:8080" \
    --entrypoint "$KWBASE_BIN" \
    "$IMAGE" \
    start-single-node \
      --insecure \
      --host=0.0.0.0 \
      --port="$SQL_PORT" \
      --http-port=8080 \
      --store=path="$CONTAINER_STORE" \
    >/dev/null
}

wait_for_kwdb() {
  local max_attempts=60
  local attempt=1

  echo "Waiting for KWDB SQL service on localhost:$SQL_PORT ..."
  while [ "$attempt" -le "$max_attempts" ]; do
    if sql -e "SELECT 1;" >/dev/null 2>&1; then
      echo "KWDB is ready."
      return
    fi

    sleep 2
    attempt=$((attempt + 1))
  done

  docker logs --tail 80 "$CONTAINER_NAME" >&2 || true
  die "KWDB did not become ready in time"
}

copy_data_to_container() {
  local extern_dir="$LOCAL_DATA_DIR/extern"

  [ -d "$extern_dir/rdb" ] || die "missing prepared data: $extern_dir/rdb"
  [ -d "$extern_dir/tsdb" ] || die "missing prepared data: $extern_dir/tsdb"

  docker exec "$CONTAINER_NAME" sh -c 'mkdir -p "$1/extern" && rm -rf "$1/extern/rdb" "$1/extern/tsdb"' sh "$CONTAINER_STORE"
  docker cp "$extern_dir/rdb" "$CONTAINER_NAME:$CONTAINER_STORE/extern/"
  docker cp "$extern_dir/tsdb" "$CONTAINER_NAME:$CONTAINER_STORE/extern/"
}

import_data() {
  echo "Importing smart-meter data into KWDB ..."
  sql -e "DROP DATABASE IF EXISTS rdb CASCADE;"
  sql -e "DROP DATABASE IF EXISTS tsdb CASCADE;"
  sql -e 'IMPORT DATABASE CSV DATA ("nodelocal://1/rdb");'
  sql -e 'IMPORT DATABASE CSV DATA ("nodelocal://1/tsdb");'
}

write_env_file() {
  local marker="# KWDB local development configuration generated by scripts/dev-kwdb.sh"

  if [ -f "$SERVER_ENV" ] && ! grep -Fqx "$marker" "$SERVER_ENV"; then
    if [ "${KWDB_DEV_OVERWRITE_ENV:-0}" != "1" ]; then
      echo "Existing server environment left unchanged: $SERVER_ENV"
      echo "Ensure it points to KWDB_HOST=localhost and KWDB_PORT=$SQL_PORT, or rerun with KWDB_DEV_OVERWRITE_ENV=1."
      return
    fi
  fi

  cat > "$SERVER_ENV" <<EOF
$marker
KWDB_HOST=localhost
KWDB_PORT=$SQL_PORT
KWDB_USER=root
KWDB_PASSWORD=
KWDB_SSL=false

PORT=3001
NODE_ENV=development
CLIENT_URL=http://localhost:3002
EOF
  echo "Wrote server environment: $SERVER_ENV"
}

show_status() {
  if ! container_exists; then
    echo "KWDB development container does not exist: $CONTAINER_NAME"
    return
  fi

  docker ps -a --filter "name=^/${CONTAINER_NAME}$" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

  if container_running && sql -e "SELECT 1;" >/dev/null 2>&1; then
    echo
    echo "RDB tables:"
    sql -d rdb -e "SHOW TABLES;" || true
    echo
    echo "TSDB tables:"
    sql -d tsdb -e "SHOW TABLES;" || true
  fi
}

stop_container() {
  if container_exists; then
    docker stop "$CONTAINER_NAME" >/dev/null
    echo "Stopped KWDB development container: $CONTAINER_NAME"
  else
    echo "KWDB development container does not exist: $CONTAINER_NAME"
  fi
}

reset_container() {
  if container_exists; then
    docker rm -f "$CONTAINER_NAME" >/dev/null
    echo "Removed KWDB development container: $CONTAINER_NAME"
  fi
}

up() {
  require_cmd docker
  prepare_data
  start_container
  wait_for_kwdb
  copy_data_to_container
  import_data
  write_env_file
  show_status
  echo
  echo "KWDB development database is ready."
  echo "Start the web app with: npm run dev"
}

main() {
  local command="${1:-up}"

  case "$command" in
    up)
      up
      ;;
    reset)
      require_cmd docker
      reset_container
      up
      ;;
    stop)
      require_cmd docker
      stop_container
      ;;
    status)
      require_cmd docker
      show_status
      ;;
    logs)
      require_cmd docker
      docker logs --tail 120 "$CONTAINER_NAME"
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      usage
      die "unknown command: $command"
      ;;
  esac
}

main "$@"
